#!/usr/bin/env python3
"""
Scans posts/*.html, reads post-title / post-date / post-category <meta> tags,
and regenerates posts.js.

Usage:
    python build.py

Add a new post by creating an HTML file in posts/ with these tags in <head>:
    <meta name="post-title"    content="Your Post Title">
    <meta name="post-date"     content="YYYY-MM-DD">
    <meta name="post-category" content="category">
"""
import re
import json
from pathlib import Path


def extract_meta(content, name):
    match = re.search(
        rf'<meta\s+name=["\']post-{name}["\']\s+content=["\']([^"\']+)["\']',
        content,
    )
    return match.group(1) if match else None


posts_dir = Path(__file__).parent / "posts"
posts = []

for html_file in sorted(posts_dir.glob("*.html")):
    content = html_file.read_text(encoding="utf-8")
    title    = extract_meta(content, "title")
    date     = extract_meta(content, "date")
    category = extract_meta(content, "category")

    if not all([title, date, category]):
        missing = [k for k, v in {"title": title, "date": date, "category": category}.items() if not v]
        print(f"WARNING: {html_file.name} is missing meta tag(s): {', '.join(missing)} — skipped")
        continue

    posts.append({
        "title":    title,
        "date":     date,
        "category": category,
        "url":      f"posts/{html_file.name}",
    })

posts.sort(key=lambda p: p["date"], reverse=True)

lines = [
    "// AUTO-GENERATED by build.py — do not edit manually.",
    "// To add a post: create an HTML file in posts/ with post-title, post-date,",
    "// and post-category <meta> tags, then run: python build.py",
    "const POSTS = [",
]
for i, p in enumerate(posts):
    comma = "," if i < len(posts) - 1 else ""
    lines.append(
        f'  {{ title: {json.dumps(p["title"], ensure_ascii=False)}, '
        f'date: {json.dumps(p["date"])}, '
        f'category: {json.dumps(p["category"])}, '
        f'url: {json.dumps(p["url"], ensure_ascii=False)} }}{comma}'
    )
lines.append("];")

out = Path(__file__).parent / "posts.js"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Generated posts.js with {len(posts)} post(s).")
