// AUTO-GENERATED by build.py — do not edit manually.
// To add a post: create an HTML file in posts/ with post-title, post-date,
// and post-category <meta> tags, then run: python build.py
const POSTS = [
  { title: "About me", date: "2026-05-12", category: "dev", url: "posts/about-me.html" },
  { title: "Tools for language learning", date: "2026-05-12", category: "language learning", url: "posts/tools-for-language-learning.html" },
  { title: "Websites for language learning", date: "2026-05-12", category: "language learning", url: "posts/websites-for-language-learning.html" },
  { title: "What is the future of languages ?", date: "2026-05-12", category: "language learning", url: "posts/what-is-the-future-of-languages.html" },
  { title: "First post, let's see if this works :D", date: "2026-05-11", category: "projects", url: "posts/first-post-lets-see-if-this-works.html" }
];
