// AUTO-GENERATED by build.py — do not edit manually.
// To add a post: create an HTML file in posts/ with post-title, post-date,
// and post-category <meta> tags, then run: python build.py
const POSTS = [
  { title: "Youtube for language learning", date: "2026-07-28", category: "language learning", url: "posts/youtube-for-language-learning.html" },
  { title: "Tools for language learning", date: "2026-05-12", category: "language learning", url: "posts/tools-for-language-learning.html" },
  { title: "Websites for language learning", date: "2026-05-12", category: "language learning", url: "posts/websites-for-language-learning.html" },
  { title: "What is the future of languages ?", date: "2026-05-12", category: "language learning", url: "posts/what-is-the-future-of-languages.html" },
  { title: "About me", date: "2026-05-11", category: "ABADOTH", url: "posts/about-me.html" }
];
